# Generated by Django 4.1.7 on 2023-02-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=30)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('duties', models.CharField(max_length=200)),
            ],
        ),
    ]
